import { Registry, Shuangpin, ZeroShengmu } from '@/core';

export const type = 'XianHe';

Registry.schema.register({
  type,
  displayName: '小鹤双拼',
  map: {
    [Shuangpin.a]: 'a',
    [Shuangpin.o]: 'o',
    [Shuangpin.e]: 'e',
    [Shuangpin.i]: 'i',
    [Shuangpin.u]: 'u',
    [Shuangpin.v]: 'v',

    [Shuangpin.ai]: 'd',
    [Shuangpin.ei]: 'w',
    [Shuangpin.ui]: 'v',
    [Shuangpin.ao]: 'c',
    [Shuangpin.ou]: 'z',
    [Shuangpin.iu]: 'q',
    [Shuangpin.ie]: 'p',
    [Shuangpin.ve]: 't',
    // [Shuangpin.er]: 'er',
    [Shuangpin.an]: 'j',
    [Shuangpin.en]: 'f',
    [Shuangpin.in]: 'b',
    [Shuangpin.un]: 'y',
    [Shuangpin.vn]: 'y',
    [Shuangpin.ang]: 'h',
    [Shuangpin.eng]: 'g',
    [Shuangpin.ing]: 'k',
    [Shuangpin.ong]: 's',

    [Shuangpin.b]: 'b',
    [Shuangpin.p]: 'p',
    [Shuangpin.m]: 'm',
    [Shuangpin.f]: 'f',
    [Shuangpin.d]: 'd',
    [Shuangpin.t]: 't',
    [Shuangpin.n]: 'n',
    [Shuangpin.l]: 'l',
    [Shuangpin.g]: 'g',
    [Shuangpin.k]: 'k',
    [Shuangpin.h]: 'h',
    [Shuangpin.j]: 'j',
    [Shuangpin.q]: 'q',
    [Shuangpin.x]: 'x',
    [Shuangpin.z]: 'z',
    [Shuangpin.c]: 'c',
    [Shuangpin.s]: 's',
    [Shuangpin.zh]: 'v',
    [Shuangpin.ch]: 'i',
    [Shuangpin.sh]: 'u',
    [Shuangpin.r]: 'r',
    [Shuangpin.y]: 'y',
    [Shuangpin.w]: 'w',

    [Shuangpin.ua]: 'x',
    [Shuangpin.uai]: 'k',
    [Shuangpin.uan]: 'r',
    [Shuangpin.uang]: 'l',
    [Shuangpin.ue]: 't',
    [Shuangpin.uo]: 'o',
    [Shuangpin.ia]: 'x',
    [Shuangpin.iao]: 'n',
    [Shuangpin.ian]: 'm',
    [Shuangpin.iang]: 'l',
    [Shuangpin.iong]: 's',
  },
  patchMap: {
    [ZeroShengmu.a]: 'aa',
    [ZeroShengmu.ai]: 'ai',
    [ZeroShengmu.an]: 'an',
    [ZeroShengmu.ang]: 'ah',
    [ZeroShengmu.ao]: 'ao',
    [ZeroShengmu.e]: 'ee',
    [ZeroShengmu.ei]: 'ei',
    [ZeroShengmu.en]: 'en',
    [ZeroShengmu.eng]: 'eg',
    [ZeroShengmu.er]: 'er',
    [ZeroShengmu.o]: 'oo',
    [ZeroShengmu.ou]: 'ou',
  },
});
